name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --ignore-engines

      - name: elm-analyse
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: elm-analyse
